---
steps:
  - script: |
      make qemu
      make wrap-$(ARCH)
    displayName: Setup ${{ parameters.arch }}
  - script: |
      BASE=${{ parameters.base }} make build-$(ARCH)
    displayName: Build ${{ parameters.arch }}
  - script: |
      echo ${{ parameters.password }} | $(DOCKER) login --username ${{ parameters.username }} --password-stdin
      make push-$(ARCH)
    displayName: Push ${{ parameters.arch }}
