---
steps:
  - template: .azure-pipelines-job.yml
    displayName: 'amd64 (Intel/AMD)'
    parameters:
      arch: amd64
      username: $(dockerLogin)
      password: $(dockerPassword)
  - template: .azure-pipelines-job.yml
    displayName: 'arm32v7 (Pi 2+ and other armhf)'
    parameters:
      arch: arm32v7
      username: $(dockerLogin)
      password: $(dockerPassword)
  - template: .azure-pipelines-job.yml
    displayName: 'arm64v8 (Pi 3+ and other ARM64)'
    parameters:
      arch: arm64v8
      username: $(dockerLogin)
      password: $(dockerPassword)
